name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.0.0 

  cupertino_icons: 1.0.5
  rxdart: 0.27.7 
  sqflite: 2.2.8+4
  path_provider: 2.0.15
  provider: 6.0.5
  retrofit: 4.0.1
  logger: 1.4.0
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.1
  retrofit_generator: 7.0.1
  build_runner: 2.4.5

  json_serializable: 6.7.0

flutter:
  uses-material-design: true
